### ISSUE TITLE
最小进入集?!

### ISSUE THREAD

**Issue by ZoomQuiet** [open-falcon/doc#1]
# 现象

- 哗, 又一家自主研发 `云运维平台` 的小伙伴了
- 但是,以往的 BAT 以及 Yahoo! 传说中的平台都是各种广告,神奇的截屏
- 可是,从来没有听说在公司以外有人用起来过

# 分析

- DevOps 平台,包含了太多硬嵌入的公司业务
- 以至根本无法简单的从平台中抽离出来
- 进而导致平台无法安装配置到其它业务场景中工作

# 建议

- 给出如何在 MAC/Win/Linux 平台上安装/调试/使用 的详细说明
- 就主机 <10 台的小微团队给出一个最小可用集
- 要知道, Google 也是从 2人团队发展起来的
- o-falcon 能进入越多的小微创业团队,意味着越多可能成为 Google 级别公司的核心运维平台 ;-)

**Comment by laiwei** [comment]
说的很好

open-falcon 是一套完整的解决方案，可以很方便的在不同的公司来部署使用

可以很方便的监控10台服务，也可以扩展到10万台服务器。

年后，整个组件，以及文档都会移动到github上。（现在还在审批阶段）

**Comment by harryshayne** [comment]
zabbix的升级版，希望能成为专为互联网而生的基础监控平台。已搭建完agent，强烈期待Server端的开源。

**Comment by jumping** [comment]
期待Server端开源，就不用自己弄了。

**Comment by laiwei** [comment]
@jumping 都会整理上来的，一个好用 可靠的监控系统，确实很有必要：）

**Comment by raysonxin** [comment]
期待。。。看了这篇（http://www.jianshu.com/p/b2f77285266c）介绍，很受启发，感觉对我们目前的物联网监控项目也很有用。

**Comment by jumping** [comment]
@laiwei @UlricQin 我每天都来看有没有新的项目放进来，非常渴望能完善整个监控体系。

**Comment by blankyao** [comment]
期待能有个和公司内部业务没啥关系的对外可用版

**Comment by jumping** [comment]
发现一个类型的项目 http://prometheus.io/

**Comment by laiwei** [comment]
@jumping prometheus 看起来还挺不错的，不过我们还没来得及研究和对比

**Comment by nethibernate** [comment]
@laiwei 大概看了一下，prometheus安装起来要复杂一些。我觉得falcon更好用一些，安装简单。现在就是不知道你们什么时候把相应的模块儿都能开源上来

**Comment by UlricQin** [comment]
代码所有组件都放上来了，如果最小安装的话，把所有组件都放到一台server上即可。然后在公司所有目标机器上部署agent即可。
