### ISSUE TITLE
Agent的ignore配置无效

### ISSUE THREAD

**Issue by jojohappy** [open-falcon/doc#14]
配置中可以进行true or false，但是配置为false时依然不会收集数据，只有删除时才会收集数据

**Comment by UlricQin** [comment]
此处的配置确实比较让人困惑，理论上此处应该配置成一个列表，而不是map，现在的逻辑是无论是true还是false，只要出现在ignore中，就不会上报，稍候我修改一下代码，如果配置成false，就继续上报

**Comment by jojohappy** [comment]
我觉得配置成列表也不错，就像gitignore一样

**Comment by UlricQin** [comment]
https://github.com/open-falcon/agent/commit/87d5399d904023bd71ded6549936cb6ee3042482 改好了，只有设置到ignore列表并且配置为true才会ignore
