### ISSUE TITLE
插件的标准输出内容的格式问题

### ISSUE THREAD

**Issue by wkshare** [open-falcon/doc#18]
[root@open-falcon-hbs01:/path/to/plugins/plugin/sys/ntp]#./600_ntp.py
[{"endpoint": "open-falcon-hbs01.bj", "tags": "", "timestamp": 1431349763, "metric": "sys.ntp.offset", "value": 0.73699999999999999, "counterType": "GAUGE", "step": 600}]

问题1：如上的输出结果，最终使用了[...]，这个中括号是否必须？
问题2：tags这个key对应的value，该如何填写？

**Comment by UlricQin** [comment]
中括号是必须的，因为plugin执行会产生多条报警数据，所以必须是个list。
tags举个例子：`"tags":"project=falcon,module=judge"`

**Comment by wkshare** [comment]
thks
