### ISSUE TITLE
存储后端

### ISSUE THREAD

**Issue by zzl0** [open-falcon/doc#2]
hi，在你们的[文章](http://www.jianshu.com/p/b2f77285266c)中看到“transfer目前支持的业务后端，有三种，judge、graph、opentsdb。judge是我们开发的高性能告警判定组件，graph是我们开发的高性能数据存储、归档、查询组件，opentsdb是开源的时间序列数据存储服务”

我想请教下哪里可以看到你们的 graph 存储引擎的更多信息？另外，你们的时间粒度是固定的吗（例如 whisper 可以自定义 `retentions = 10s:6h,1min:6d,10min:1800d`）？

**Comment by laiwei** [comment]
graph的文档和代码，会近期更新上来

时间粒度，是在代码中配置死的，如果要自定义，需要更改代码。

数据存储仍然是rrdtool的格式，只是做成了分布式，且做了性能上的调优（IO可以减小几十倍）

**Comment by zzl0** [comment]
@laiwei 感谢回复，期待。可以简单回答下 IO 上的的优化吗，有做合并指标、延迟写（采样的传递，如 10 秒粒度的数据向 60s 粒度的传递），或者其他？

**Comment by laiwei** [comment]
@zzl0 IO优化主要就是：
1. 充分利用内存，把多次写磁盘（目前是30次）合并为一次写磁盘。
2. 刷新磁盘的操作，组织成单个队列来刷新，打散到每一秒钟

12小时内，存储的是原始数据，超过12小时的数据，默认就会老化存储

**Comment by zzl0** [comment]
@zzl0 thx
