### ISSUE TITLE
ops-updater的管理问题

### ISSUE THREAD

**Issue by wkshare** [open-falcon/doc#23]
```
2015/05/28 23:05:26 heartbeat.go:64: { [<Name:falcon-agent, Version:3.1.4, Tarball:http://127.0.0.1:2000/falcon, Md5:8c2662002401eb724e6aa177b31bb2d6, Cmd:start>]}
2015/05/28 23:05:26 start.go:89: wget -q 8c2662002401eb724e6aa177b31bb2d6/falcon-agent-3.1.4.tar.gz.md5 -O falcon-agent-3.1.4.tar.gz.md5 fail exit status 4
```
如果meta端配置了md5，那么updater的日志中会有如上的东东，wget部分。
updater无法正常更新agent。

另外，如果不更新agent的包名，是否无法正常更新agent？

**Comment by UlricQin** [comment]
这个md5配置的不对，不能在md5字段直接配置一个md5，就像blog中描述的，md5是一个文件 `${name}-${version}.tar.gz.md5`，这个md5字段应该配置成一个下载地址目录，通常都是留空的，因为md5文件通常是和tarball放在一起的

我们要更新agent，通常版本号会发生变化，所以包名会发生变化，此时会正常更新agent，如果这些版本号和包名都没有发生变化，单机updater组件发现本地已经有了这个缓存文件，是不会重复下载的，于是就不会更新了

**Comment by wkshare** [comment]
了解。thks
