### ISSUE TITLE
judge是在收到transfer数据作报警判断，那么怎么配置agent.alive的报警？

### ISSUE THREAD

**Issue by dotwoo** [open-falcon/doc#25]
judge先从hbs获取所有策略列表，静等Transfer的数据转发。 每收到一条Transfer转发过来的数据，立即找到这条数据关联的Strategy、Expression，然后做阈值判断。

alive类型的如果agent存在，会发送alive，如果agent不存在。应该judge就收不到alive数据，这时候judge怎么对这个类型做报警？

**Comment by laiwei** [comment]
是这样的，如果agent挂掉了，那么告警就无法判定了。

从两个方面来看这个问题哈

1. agent从来没有挂过。
2. 我们正在做一个nodata的功能，即某个指标超过多久没有上报过，就触发告警。

thx

**Comment by dotwoo** [comment]
了解，谢谢。
