### ISSUE TITLE
业务采集的数据推荐多久post到agent

### ISSUE THREAD

**Issue by nethibernate** [open-falcon/doc#26]
业务自己采集的数据，是采集一条就post到本机的agent，还是积攒一定数量再post。
我看文档中，plugin推荐是攒500条发送，业务自己采集的数据也推荐积攒一定数量再post么？

**Comment by laiwei** [comment]
@nethibernate 

每次有多少数据，就发送多少数据。

比如每一分钟，总共就只有10条数据，那么就一次性发送10条给agent

再比如每一分钟，总共有2000条数据，那么建议，分四次发送给agent（只是建议而已，你也可以一次性把2000条数据全部post给agent）
