### ISSUE TITLE
安装Dashboard卡壳

### ISSUE THREAD

**Issue by decker502** [open-falcon/doc#3]
按文档安装Dashboard后，运行报错，望指导，多谢

````
 ./control start
I require gunicorn but it's not installed.  Aborting.
````

**Comment by laiwei** [comment]
pip install gunicorn

请确保gunicorn安装成功了。
gunicorn的安装是在pip_requirements.txt中写的
你检查下 pip install -r pip_requirements.txt 是否有报错

**Comment by decker502** [comment]
可以了，是因为没有安装 mysql-devel,导致mysql-python没有安装成功，应该是错误提示不准确，多谢了
