### ISSUE TITLE
dashboard中查询不到数据

### ISSUE THREAD

**Issue by wkshare** [open-falcon/doc#5]
查看graph配置：
cat graph_backends.txt 
"graph-00 127.0.0.1:6070"

query运行日志：
root@zabbix-master:/home/work/open-falcon/query# ./control tail
2015/05/22 14:42:31 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:45 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:45 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:48 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:48 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:51 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:43:51 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:44:02 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:44:02 [E] query one fail: unknown port tcp/6070" [graph.go:42]
2015/05/22 14:44:02 [E] query one fail: unknown port tcp/6070" [graph.go:42]

查看graph监听端口：
netstat -ntlp | grep 6070
tcp6       0      0 :::6070                 :::*                    LISTEN      30171/falcon-graph

查看graph运行日志：
 ../graph/control tail
2015/05/22 14:03:46 cfg.go:80: read config file: cfg.json successfully
2015/05/22 14:03:46 db.go:27: g.InitDB, ok
2015/05/22 14:03:46 index.go:14: index:Start, ok
2015/05/22 14:03:46 main.go:23: 30171 register signal notify
2015/05/22 14:03:46 http.go:87: http listening 0.0.0.0:6071
2015/05/22 14:03:46 rpc.go:53: rpc listening 0.0.0.0:6070

**Comment by UlricQin** [comment]
执行`ss -tln|grep 60`看一下
贴一下graph的配置

**Comment by UlricQin** [comment]
`telnet 127.0.0.1 6070`看看本机6070端口是否在正常监听

**Comment by wkshare** [comment]
graph日志：
cat cfg.json 
{
    "pid": "/home/work/open-falcon/graph/var/app.pid",
    "log": "info",
    "debug": false,
    "debugChecksum": "nil",
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:6071"
    },
    "rpc": {
        "enabled": true,
        "listen": "0.0.0.0:6070"
    },
    "rrd": {
        "storage": "/home/work/data/6070"
    },
    "db": {
        "dsn": "root:@tcp(localhost:3366)/graph?loc=Local&parseTime=true",
        "maxIdle": 4
    }
}
root@zabbix-master:/home/work/open-falcon/graph# ./control tail
2015/05/22 14:03:46 db.go:27: g.InitDB, ok
2015/05/22 14:03:46 index.go:14: index:Start, ok
2015/05/22 14:03:46 main.go:23: 30171 register signal notify
2015/05/22 14:03:46 http.go:87: http listening 0.0.0.0:6071
2015/05/22 14:03:46 rpc.go:53: rpc listening 0.0.0.0:6070

telnet是可以的
telnet 127.0.0.1 6070
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

**Comment by wkshare** [comment]
找到原因：
graph_backends.txt配置文件中的graph列表，不要使用引号。
"graph-00 127.0.0.1:6070"  -> graph-00 127.0.0.1:6070

错误的日志
2015/05/22 14:50:19 [I] create the pool: "graph-00 127.0.0.1:6070" [backends.go:121]

正常的日志
2015/05/22 15:05:55 [I] create the pool: graph-00 127.0.0.1:6070 [backends.go:121]
