### ISSUE TITLE
alarm启动错误

### ISSUE THREAD

**Issue by wkshare** [open-falcon/doc#7]
2015/05/22 16:06:25 cfg.go:81: read config file: cfg.json successfully
2015/05/22 16:06:25 [config.go:285] [W] open /home/work/open-falcon/alarm/conf/app.conf: no such file or directory 
2015/05/22 16:06:25 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command
2015/05/22 16:06:25 [app.go:103] [I] http server Running on 0.0.0.0:7070
2015/05/22 16:06:26 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command
2015/05/22 16:06:27 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command
2015/05/22 16:06:28 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command
2015/05/22 16:06:29 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command
2015/05/22 16:06:30 reader.go:52: get alarm event from redis fail: ERR wrong number of arguments for 'brpop' command

redis启动情况，telnet可以正常访问：
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      11312/redis-server

求助

**Comment by wkshare** [comment]
贴上alarm的配置：
{
    "debug": true,
    "uicToken": "",
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:7070"
    },
    "queue": {
        "sms": "/sms",
        "mail": "/mail"
    },
    "redis": {
        "addr": "127.0.0.1:6379",
        "maxIdle": 5,
        "highQueues": [
            "event:p0",
            "event:p1",
            "event:p2",
            "event:p3",
            "event:p4",
            "event:p5",
            "event:p6"
        ],
        "lowQueues": [
        ],
        "userSmsQueue": "/queue/user/sms",
        "userMailQueue": "/queue/user/mail"
    },
    "api": {
        "portal": "http://falcon.example.com",
        "uic": "http://uic.example.com",
        "links": "http://link.example.com"
    }
}

**Comment by UlricQin** [comment]
这个地方代码写挫了，把`"event:p6"`放到lowQueues中，剩下5个放到highQueues中。因为lowQueues中如果是空的就报错了

**Comment by UlricQin** [comment]
另外你的api部分都要配置成实际ip，那些域名都只是例子哈

**Comment by wkshare** [comment]
好的，谢谢。

哎呀，多出来3个问题：
1、日志中这个警告，是否重要：
2015/05/22 16:20:31 [config.go:285] [W] open /home/work/open-falcon/alarm/conf/app.conf: no such file or directory 
3、api中，是否直接配置内网地址就可以？
4、dashboard、alarm是否使用了uic来验证？

**Comment by UlricQin** [comment]
- 1. 那个log是我用了beego框架但是没有使用他们的配置文件，所以warning了不用care
- 2. api中的地址都配置为内网地址即可
- 3. dashboard和alarm没用用户的概念，任何人都可以查看，没有权限控制

**Comment by wkshare** [comment]
谢谢 @UlricQin
