### ISSUE TITLE
寻求帮助 add host 找不到机器。 OS:ubuntu1410

### ISSUE THREAD

**Issue by haigame** [open-falcon/doc#9]
1-------------
/home/work/open-falcon/agent# vim cfg.json 

{
    "debug": true,
    "hostname": "",
    "ip": "",
    "plugin": {
        "enabled": false,
        "dir": "./plugin",
        "git": "https://coding.net/ulricqin/plugin.git",
        "logs": "./logs"
    },
    "heartbeat": {
        "enabled": true,
        "addr": "",
        "interval": 60,
        "timeout": 1000
    },
    "transfer": {
        "enabled": true,
        "addr": "127.0.0.1:8433",
        "interval": 60,
        "timeout": 1000
    },
    "http": {
        "enabled": true,
        "listen": ":1988"
    },
    "collector": {
        "ifacePrefix": ["eth", "em"]

把heartbeat那项enabled设置为true， -->已修改，并重启./control restart
并配置上hbs的rpc地址 <--麻烦问下这个配置是在哪里配置。
2-------------
drwxr-xr-x  2 root  root     4096  5月 22 14:05 var/
root@ub14IP239monitorMI:~/open-falcon/hbs# vim cfg.json 

{
    "debug": true,
    "database": "falcon_portal:abc1234@tcp(127.0.0.1:3306)/falcon_portal?loc=Local&parseTime=true",
    "hosts": "",
    "maxIdle": 100,
    "listen": ":6030",
    "trustable": [""],
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:6031"
    }
}

---
  "database": "falcon_portal:abc1234@tcp(127.0.0.1:3306)/falcon_portal?loc=Local&parseTime=true", 是用这个。
还是用这个。
  "database": "root:abc1234@tcp(127.0.0.1:3306)/falcon_portal?loc=Local&parseTime=true",

#mysql -uroot -pabc1234 -h127.0.0.1 ,都能正常连接mysql
#mysql -ufalcon_portal -pabc1234 -h127.0.0.1 ,都能正常连接mysql

~agent就可以和hbs心跳了 ,这个有命令检查下吗，不知是是在哪配置错了，麻烦指点一，二，谢谢

**Comment by UlricQin** [comment]
```
"heartbeat": {
"enabled": true,
"addr": "",
"interval": 60,
"timeout": 1000
},
```

此处的addr就是用来配置hbs地址的，配置成hbs的rpc端口地址

**Comment by UlricQin** [comment]
两个账号如果都可以联通的话，随便哪个都行。但是连上去还要有权限操作falcon_portal这个数据库才行，用root肯定没问题，falcon_portal这个账号肯定是你自己创建的了，希望你的授权也是OK的，否则就老老实实用root吧

**Comment by haigame** [comment]
谢谢^^ 2个用户mysql授权都ok的，都测试过了。
addr": "",   我这个都在一台机器上，是填：0.0.0.0:6031，还是填127.0.0.1:6031 ，还是内网IP:192.168.1.239:6031

**Comment by haigame** [comment]
成功了，填127.0.0.1:6030   , success:  ，谢谢 UlricQin  ,辛苦你一天了。好员工。^^

**Comment by haigame** [comment]
在，falcon_portal; 里。selcet * from host;
能查到 主机了。谢谢。

**Comment by UlricQin** [comment]
辛苦费20打到哥支付宝，晚饭你得请

**Comment by haigame** [comment]
你头像真帅

**Comment by haigame** [comment]
支付宝账号发我下、20元蛋炒饭，马上过来。
